import { MigrationInterface, QueryRunner } from "typeorm";

export class MyFirst1784553785743 implements MigrationInterface {
    name = 'MyFirst1784553785743'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_bbb8e4640ffea3ac7108e784f92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b3b507508cd0f86a5b2e92345"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'BUYER', 'FARMER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."users_role_enum" NOT NULL DEFAULT 'BUYER', "businessName" character varying, "userName" character varying NOT NULL, "phoneNumber" character varying, "securityQuestion" character varying, "securityAnswer" character varying, "password" character varying, "isComplete" boolean NOT NULL DEFAULT false, "location" text, "address" character varying, "email" character varying, "profilePic" character varying, "accountNumber" character varying, "accountName" character varying, "bankName" character varying, CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_originstate_enum" AS ENUM('Kano', 'Kaduna', 'Gombe', 'Plateau')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_destinationcity_enum" AS ENUM('Lagos', 'Ibadan', 'Port Harcourt', 'Onitsha')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_packagingtype_enum" AS ENUM('Sack', 'Raffia Basket', 'Plastic crate', 'Wooden crate')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_season_enum" AS ENUM('Dry Season', 'Rainy Season')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_transportmode_enum" AS ENUM('Covered Truck', 'Refrigerated Reefer Van', 'Traditional Open Truck')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_storagetype_enum" AS ENUM('Cold Storage', 'No Storage', 'Open Storage', 'Shaded Storage')`);
        await queryRunner.query(`CREATE TYPE "public"."logistics_damagelevel_enum" AS ENUM('Low', 'Moderate', 'None', 'Severe')`);
        await queryRunner.query(`CREATE TABLE "logistics" ("logisticId" uuid NOT NULL DEFAULT uuid_generate_v4(), "originState" "public"."logistics_originstate_enum" NOT NULL, "destinationCity" "public"."logistics_destinationcity_enum" NOT NULL, "packagingType" "public"."logistics_packagingtype_enum" NOT NULL, "season" "public"."logistics_season_enum" NOT NULL, "routeDistanceKm" numeric(10,2) NOT NULL, "transportMode" "public"."logistics_transportmode_enum" NOT NULL, "quantitySentCrates" integer NOT NULL, "hoursSinceHarvestAtDispatch" numeric(5,2) NOT NULL, "coldStorageAvailable" boolean NOT NULL DEFAULT false, "storageType" "public"."logistics_storagetype_enum", "damageLevel" "public"."logistics_damagelevel_enum" NOT NULL DEFAULT 'None', "plateNumber" character varying NOT NULL, "driverName" character varying, "driverPhoneNumber" character varying, "userId" uuid NOT NULL, "orderId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_5af3957a2bf7a7ff8342d9115a" UNIQUE ("orderId"), CONSTRAINT "PK_e6d9d7cfe62919f749000a8ccd2" PRIMARY KEY ("logisticId"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_deliverystatus_enum" AS ENUM('Not Started', 'In Transit', 'Delivered')`);
        await queryRunner.query(`CREATE TABLE "orders" ("orderId" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantityRequested" integer NOT NULL, "logisticStatus" character varying NOT NULL DEFAULT 'Not Confirmed', "deliveryStatus" "public"."orders_deliverystatus_enum" NOT NULL DEFAULT 'Not Started', "productId" uuid NOT NULL, "buyerId" uuid NOT NULL, "logisticsId" uuid, CONSTRAINT "REL_78d7f316272018447b999967b1" UNIQUE ("logisticsId"), CONSTRAINT "PK_41ba27842ac1a2c24817ca59eaa" PRIMARY KEY ("orderId"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum" AS ENUM('CARD', 'BANK_TRANSFER', 'USSD', 'WALLET')`);
        await queryRunner.query(`CREATE TABLE "payments" ("paymentId" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(12,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL DEFAULT 'CARD', "stripePaymentIntentId" character varying, "gatewayMetadata" jsonb, "orderId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_57059f281caef51ef1c15adaf35" UNIQUE ("stripePaymentIntentId"), CONSTRAINT "PK_ae0b0903f275c81d8a2a45ce3b5" PRIMARY KEY ("paymentId"))`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "spoilageTime"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "userName"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "REL_bbb8e4640ffea3ac7108e784f9"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "userUserId"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "estimatedSpoilageTime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "products" ADD "harvestDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "harvestTime" TIME NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."products_originstate_enum" AS ENUM('Kano', 'Kaduna', 'Gombe', 'Plateau')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "originState" "public"."products_originstate_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."products_destinationmarket_enum" AS ENUM('Lagos', 'Ibadan', 'Port Harcourt', 'Onitsha')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "destinationMarket" "public"."products_destinationmarket_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "quantitySentCrates" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."products_packagingtype_enum" AS ENUM('Sack', 'Raffia Basket', 'Plastic crate', 'Wooden crate')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "packagingType" "public"."products_packagingtype_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."products_transportmode_enum" AS ENUM('Covered Truck', 'Refrigerated Reefer Van', 'Traditional Open Truck')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "transportMode" "public"."products_transportmode_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "coldStorageAvailable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."products_storagetype_enum" AS ENUM('Cold Storage', 'No Storage', 'Open Storage', 'Shaded Storage')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "storageType" "public"."products_storagetype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."products_ripenesslevel_enum" AS ENUM('UNRIPE', 'RIPE', 'OVER_RIPE')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "ripenessLevel" "public"."products_ripenesslevel_enum" NOT NULL DEFAULT 'RIPE'`);
        await queryRunner.query(`CREATE TYPE "public"."products_initialdamagelevel_enum" AS ENUM('Low', 'Moderate', 'None', 'Severe')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "initialDamageLevel" "public"."products_initialdamagelevel_enum" NOT NULL DEFAULT 'None'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "farmerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "walletId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8e246dfcb84930971b5300d8cad" PRIMARY KEY ("walletId")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "balance" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "currency" character varying NOT NULL DEFAULT 'NGN'`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "isPayoutSetupCompleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "UQ_2ecdb33f23e9a6fc392025c0b97" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "distance" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "rating" numeric(3,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a6b3c434392f5d10ec171043666"`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "productId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "rating" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "logistics" ADD CONSTRAINT "FK_09fab00a9b763b4aa31c75c830b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logistics" ADD CONSTRAINT "FK_5af3957a2bf7a7ff8342d9115a7" FOREIGN KEY ("orderId") REFERENCES "orders"("orderId") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_5c124086aa5e7d3bc35331eea60" FOREIGN KEY ("farmerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products"("productId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_48770372f891b9998360e4434f3" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8624dad595ae567818ad9983b33" FOREIGN KEY ("productId") REFERENCES "products"("productId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_78d7f316272018447b999967b12" FOREIGN KEY ("logisticsId") REFERENCES "logistics"("logisticId") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("orderId") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_78d7f316272018447b999967b12"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8624dad595ae567818ad9983b33"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_48770372f891b9998360e4434f3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a6b3c434392f5d10ec171043666"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_5c124086aa5e7d3bc35331eea60"`);
        await queryRunner.query(`ALTER TABLE "logistics" DROP CONSTRAINT "FK_5af3957a2bf7a7ff8342d9115a7"`);
        await queryRunner.query(`ALTER TABLE "logistics" DROP CONSTRAINT "FK_09fab00a9b763b4aa31c75c830b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "rating" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "productId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products"("productId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "rating" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "distance" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "UQ_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "isPayoutSetupCompleted"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "balance"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8e246dfcb84930971b5300d8cad"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "farmerId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "initialDamageLevel"`);
        await queryRunner.query(`DROP TYPE "public"."products_initialdamagelevel_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "ripenessLevel"`);
        await queryRunner.query(`DROP TYPE "public"."products_ripenesslevel_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "storageType"`);
        await queryRunner.query(`DROP TYPE "public"."products_storagetype_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "coldStorageAvailable"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "transportMode"`);
        await queryRunner.query(`DROP TYPE "public"."products_transportmode_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "packagingType"`);
        await queryRunner.query(`DROP TYPE "public"."products_packagingtype_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "quantitySentCrates"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "destinationMarket"`);
        await queryRunner.query(`DROP TYPE "public"."products_destinationmarket_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "originState"`);
        await queryRunner.query(`DROP TYPE "public"."products_originstate_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "harvestTime"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "harvestDate"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "estimatedSpoilageTime"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "userUserId" uuid`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "REL_bbb8e4640ffea3ac7108e784f9" UNIQUE ("userUserId")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "userName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "spoilageTime" TIMESTAMP NOT NULL`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_deliverystatus_enum"`);
        await queryRunner.query(`DROP TABLE "logistics"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_damagelevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_storagetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_transportmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_season_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_packagingtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_destinationcity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logistics_originstate_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7b3b507508cd0f86a5b2e92345" ON "products" USING btree ("productId") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_bbb8e4640ffea3ac7108e784f92" FOREIGN KEY ("userUserId") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
